client/src/App.css

App.css 파일 수정
- 전역적으로 사용할 변수 추가
- padding: 0 추가

[design] 전역적으로 사용할 변수 추가

---

client/src/App.js
client/src/components/main/Main.js
client/src/components/main/MainHeader.js
client/src/components/main/Nav.js

- ex) 회원정보 구현
- ex) 회원 가입 기능 추가
- ex) 회원 로그인 기능 추가
- ex) 회원 로그아웃 기능 추가
- 작성예시

docs: 컴포넌트 정리

---

client/src/components/main/Main.js

Main.js 수정
- props 추가
- 스타일 수정

[design] Main.js 수정

---

client/src/App.js
client/src/components/main/Footer.js
client/src/components/main/Main.js
client/src/components/main/MainHeader.js
client/src/components/main/Navigation.js
client/src/components/main/SubHeader.js
client/src/components/ui/LongButton.js
client/src/components/ui/ShortButton.js

- docs: 문서 명칭 수정
- ex) 회원 가입 기능 추가
- ex) 회원 로그인 기능 추가
- ex) 회원 로그아웃 기능 추가
- 작성예시

docs: 문서 명칭 수정

---

client/package-lock.json
client/package.json
client/src/components/useStore.js
client/src/pages/Home.js

- ex) 회원정보 구현
- ex) 회원 가입 기능 추가
- ex) 회원 로그인 기능 추가
- ex) 회원 로그아웃 기능 추가
- 작성예시

Feat/fe/mg: 

---

client/src/App.css
client/src/App.js
client/src/components/main/Main.js
client/src/components/main/MainHeader.js
client/src/components/main/Navigation.js
client/src/pages/Home.js

- [design] 공통 레이아웃 수정
- ex) 회원 가입 기능 추가
- ex) 회원 로그인 기능 추가
- ex) 회원 로그아웃 기능 추가
- 작성예시

[design] 공통 레이아웃 수정

---

client/package.json
client/src/App.css
client/src/pages/ItemDetail.js

상품 세부 페이지 화면 및 기능 구성
- package.json: 리뷰 작성 기능 구현을 위한 react-quill, react-simple-star-rating 라이브러리 설치
- App.css: red 색상 추가
- ItemDetail.js: 기본적인 화면 구성 완료, 기능 구현은 진행 중

[feat] 상품 세부 페이지 화면 구성

---

server/EverybodyChachapark/src/docs/asciidoc/EverbodyChachapark.adoc
server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/EverybodyChachaparkApplication.java
server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/auth/SecurityConfiguration.java
server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/domain/review/controller/ReviewController.java
server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/domain/review/dto/ReivewDto.java
server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/response/MultiResponseDto.java
server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/response/PageInfo.java
server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/response/SingleResponseDto.java
server/EverybodyChachapark/src/main/resources/static/docs/EverbodyChachapark.html
server/EverybodyChachapark/src/test/java/com/DuTongChitongYutong/EverybodyChachapark/slice/review/ReviewControllerTest.java
server/EverybodyChachapark/src/test/java/com/DuTongChitongYutong/EverybodyChachapark/util/ApiDocumentUtils.java

- feat: Review기능 API 명세서 생성
1. feat: review 생성 조회 Controller 구현
- 기초적인 MVC 구현
- Stub Data를 바탕으로 Slice Test Case
- 미 구현 된 Spring Security 오류를 방지하기 위해 SecurityConfiguration.class 생성
- Test Case에서 Security 권한에 막혀 정상적으로 구동이 불가능 하는 문제를 Mock Security Bean을 생성하여 적용하는 @AutoConfigureMockMvc(addFilters = false)로 처리
<br>
2. feat: Review기능 API 명세서 생성
- Slice Test Case를 바탕으로 Rest Docs 출력 및 생성
- Related to: #4

feat: Review기능 API 명세서 생성

---

client/src/pages/ItemDetail.js

리뷰 작성 부분 코드 변경
- ReactQuill 라이브러리 사용 대신에 textarea와 input으로 리뷰 내용과 이미지를 첨부할 수 있도록 변경

[refactor] 리뷰 작성 부분 코드 변경

---

client/src/App.css
client/src/pages/AdminNewItem.js

- 상품 생성 페이지 화면 구현
- 상품 대표 이미지 첨부, 삭제, 미리보기 기능
- 각각의 input창을 입력했을 때만 폼 제출하는 기능
- App.css
- 색상 변수 추가
- 추후 유효성 검증 로직을 추가해야 함

[feat] 상품 생성 페이지 화면 구현

---

client/src/components/shoppingComponents/ShoppingItems.js
client/src/components/store.js

-장바구니 체크박스 구현
store.js: 상품목록 삭제
ShoppingItems.js : 체크박스 구현
- 작성예시

[feat] 장바구니 체크박스 구현

---

client/src/components/main/MainLayout.js
client/src/pages/AdminNewItem.js
client/src/pages/ItemDetail.js
client/src/pages/Mypage.js

마이페이지 화면 구현 및 MainLayout 컴포넌트 추가
- MyPage.js
- 마이페이지 화면 구현
- MainLayout.js
- Main 컴포넌트 아래에 사용할 수 있는 공통 컴포넌트 생성
- AdminNewItem.js, ItemDetail.js
- MainLayout 컴포넌트 사용해서 디자인리팩토링

[design] 마이페이지 화면 구현 및 MainLayout 컴포넌트 추가

---

client/src/components/main/Footer.js
client/src/components/shoppingComponents/ShippingInformation.js
client/src/components/shoppingComponents/ShoppingItems.js
client/src/pages/ShoppingCart.js

상품구매버튼추가 , footer수정
ShippingInformation.js : 상품구매버튼 추가 및 배송지 미입력시 알림창
ShoppimgCart.js Footer 추가
Footer.js : 높이 조절

[feat] 상품구매버튼추가 , footer수정

---

client/public/index.html
client/src/pages/AdminNewItem.js
client/src/pages/Mypage.js

- index.html, AdminNewItem.js 필요없는 코드 삭제 및 마이페이지 수정 기능 추가
- index.html
- 필요 없는 코드 삭제
- 기존에 있던 기본 템플릿 내용 변경
- 필요 없는 코드 삭제
- Mypage.js
- 프로필 이미지, 닉네임, 소개글 수정 기능 추가
- 추후 서버에 변경된 내용 post하는 기능 추가 필요

[refactor] index.html, AdminNewItem.js 필요없는 코드 삭제 [feat] 마이페이지 수정 기능 추가

---

client/src/components/main/Footer.js
client/src/pages/AdminNewItem.js
client/src/pages/Mypage.js

마이페이지와 상품 생성 페이지에 Footer 추가
- Mypage.js, AdminNewItem.js
- Footer 컴포넌트 추가
- Footer.js
- 주석 삭제
- width: 100%으로 변경

[design] 마이페이지와 상품 생성 페이지에 Footer 추가

---

client/src/components/shoppingComponents/ShoppingItems.js

장바구니 아이템 없을 시 화면표시
ShoopingItem.js : 장바구니 아이템 없을 시 화면표시

[feat] 장바구니 아이템 없을 시 화면표시

---

client/src/App.js
client/src/pages/AdminNewItem.js

App.js, AdminNewItem.js 화면 레이아웃 수정
- App.js
- 글자 간격 조절
- 사진 첨부 시 footer와 겹치는 오류 해결

[design] App.js, AdminNewItem.js 화면 레이아웃 수정

---

client/src/components/review/ReadReviews.js
client/src/components/review/ReviewForm.js
client/src/pages/ItemDetail.js

상품 상세페이지 컴포넌트 분리
- 리뷰 관련된 컴포넌트 분리
- ReadReviews.js
- 리뷰 read 기능을 하는 컴포넌트 추가
- 리뷰 작성 및 수정 시 사용하는 컴포넌트 추가
- 상품 상세페이지
- 상품 대표이미지 및 상품 세부 설명 get 요청 시 잘 받아오는지 확인 필요합니다.
- 리뷰 관련 컴포넌트
- CUD에 해당하는 기능 추가 필요

[refactor] 상품 상세페이지 컴포넌트 분리

---

client/package-lock.json
client/package.json
client/src/components/shoppingComponents/ShippingInformation.js
client/src/components/shoppingComponents/ShoppingItems.js
client/src/pages/Login.js
client/src/pages/SignUp.js

[feat] login 토큰 쿠키저장 ,  회원가입 post
- SignUp .js : 응답값 post
- ShippingInformation.js , ShoppingItems : 변수명 수정
- login.js : 토큰 값 쿠키에 저장 
- package.json :   js-cookie, jwt-decode, react-intersection-observer 설치

[feat] login 토큰 쿠키저장 ,  회원가입 post

---

server/EverybodyChachapark/src/docs/asciidoc/EverbodyChachapark.adoc
server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/domain/product/controller/ProductController.java
server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/domain/product/dto/ProductDto.java
server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/domain/product/entity/Product.java
server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/domain/product/facade/ProductFacade.java
server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/domain/product/service/ProductService.java
server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/response/MultiResponseDto.java
server/EverybodyChachapark/src/test/java/com/DuTongChitongYutong/EverybodyChachapark/slice/member/MemberControllerTest.java
server/EverybodyChachapark/src/test/java/com/DuTongChitongYutong/EverybodyChachapark/slice/product/ProductControllerTest.java
server/EverybodyChachapark/src/test/java/com/DuTongChitongYutong/EverybodyChachapark/slice/review/ReviewControllerTest.java

[feat] Product 도메인 썸네일 이미지 기능 적용
- [feat] Product 도메인 썸네일 이미지 기능 적용
- Related To: #17, #5

[feat] Product 도메인 썸네일 이미지 기능 적용

---

server/EverybodyChachapark/src/docs/asciidoc/EverbodyChachapark.adoc
server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/domain/cart/controller/CartController.java
server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/domain/cart/dto/CartDto.java
server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/domain/cart/entity/Cart.java
server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/domain/cart/fasade/CartFacade.java
server/EverybodyChachapark/src/test/java/com/DuTongChitongYutong/EverybodyChachapark/slice/cart/CartControllerTest.java

- 장바구니 docs 로직 구현
- 장바구니 docs 로직 구현 완료

[Feat] Cart docs 추가

---

client/src/pages/ItemDetail.js

상품 상세 페이지 상품 수정 버튼 및 상품 삭제 버튼 추가
- 상품 수정 버튼 및 상품 삭제 버튼 추가
기능은 아직 구현 중입니다.

[feat] 상품 수정 버튼 및 상품 삭제 버튼 추가

---

client/src/pages/Login.js
client/src/pages/SignUp.js

[add] 로그인,회원가입 성공시 화면 이동
-login.js : 쿠키값 저장 , 로그인 성공 시 아이템목록 화면으로 이동
-SignUp.js : 회원가입 성공시 로그인 화면으로 이동
- 작성예시

[add] 로그인,회원가입 성공시 화면 이동

---

server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/domain/member/dto/MemberDto.java
server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/domain/member/entity/Member.java
server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/domain/member/mapper/MemberMapper.java
server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/domain/member/service/MemberService.java
server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/security/dto/LoginDto.java
server/EverybodyChachapark/src/test/java/com/DuTongChitongYutong/EverybodyChachapark/slice/member/MemberControllerTest.java
server/EverybodyChachapark/src/test/java/com/DuTongChitongYutong/EverybodyChachapark/slice/security/CustomFilterConfigurerTest.java

- 회원 comment 로직 추가
- 회원 comment 로직 추가
- docs 파일 수정 및 build 완료

[Feat] 회원 comment 로직 추가

---

client/src/components/api/itemDetailAPI.js
client/src/components/review/ReadReviews.js
client/src/components/review/ReviewForm.js
client/src/pages/ItemDetail.js

상품 리뷰 수정, 삭제 기능 리팩토링
- itemDetailAPI.js
- 상품 상세 페이지에서 사용하는 api 함수 파일 생성
- ReadReviews.js
- styled component css className 변경
- 리뷰 사진 받아오도록 수정
- 리뷰 삭제 기능 추가
- 디자인 수정
- 상품 리뷰 생성, 수정 기능 리팩토링
- 필요없는 코드 삭제
- 상품 장바구니 담는 기능 추가
- 상품 삭제 및 등록 버튼 추가
- 상품 리뷰 수정시 별이 0으로 초기화되도록 수정 필요

[refactor] 상품 리뷰 수정, 삭제 기능 리팩토링

---

client/src/components/review/ReadReviews.js
client/src/components/review/ReviewForm.js
client/src/pages/ItemDetail.js

상품 상세페이지 및 리뷰 기능 리팩토링
- ReadReviews.js
- 유저 프로필 이미지, 리뷰 이미지 받아서 화면에 보여주도록 수정
- 리뷰 작성일, 리뷰 수정일 추가
- 입력창에 required 속성 추가
- 상품명, 상품 대표 이미지 화면에 표시하도록 수정

[refactor] 상품 상세페이지 및 리뷰 기능 리팩토링

---

client/src/components/api/itemDetailAPI.js

getProductReviews 함수 페이지 0부터 받아오도록 수정

[refactor] getProductReviews 함수 페이지 0부터 받아오도록 수정

---

client/src/components/review/ReviewForm.js
client/src/pages/ItemDetail.js

[design] 상품 상세 페이지 상품 부제목 추가 [fix] 리뷰 이미지 null 처리
- 리뷰 이미지 첨부하지 않아도 post 할 수 있도록 수정
- 상품 부제목 화면에 표시하도록 수정

[design] 상품 상세 페이지 상품 부제목 추가 [fix] 리뷰 이미지 null 처리

---

client/package-lock.json
client/package.json
client/src/Paging.css
client/src/components/api/itemAPI.js
client/src/components/itemList/ItemListItem.js
client/src/components/main/MainHeader.js
client/src/components/ui/MainCarousel.js
client/src/components/ui/Pagination.js
client/src/components/ui/SubCarousel.js
client/src/pages/AdminNewItem.js
client/src/pages/ItemDetail.js
client/src/pages/ItemList.js

- [feat] 상품 목록페이지, 등록 및 삭제 기능 구현 및 변경
- [style] 일부 파일  import 위치 수정
- [chore] react-js-pagination install
- [feat][refactor] 전체 상품 조회 리팩토링, 카테고리 및 검색 상품 조회 기능 구현
- [feat] 상품 목록 페이지네이션 기능 구현
- [feat] 상품 등록, 상품 수정 기능 수정
- [refactor] 헤더 마이페이지 이동 경로 추가
- [refactor] 상세 페이지 콘텐츠 태그 보이는 현상 파싱처리
- 은지님 ItemDetail 콘텐츠 태그 그대로 렌더링되는 부분 파싱처리해서 태그 안보이게 수정했습니다
- 페이지네이션 관련해서 기능적인 이슈는 없습니다

[feat] 상품 목록페이지, 등록 및 삭제 기능 구현 및 변경 + 상품 세부페이지 일부 수정

---

client/src/App.js
client/src/pages/ItemDetail.js

이미 장바구니에 담은 상품 담은 경우  경고 메세지 출력
- App.js
- path 오타 수정
- 이미 장바구니에 담은 상품 담은 경우  경고 메세지 출력

[fix] 이미 장바구니에 담은 상품 담은 경우  경고 메세지 출력

---

client/src/App.js
client/src/components/main/MainHeader.js

로그인 시 헤더에  프로필 이미지 표시
- MainHeader.js
- 로그인하면 헤더 마이페이지에 프로필 이미지 표시
- App.js
- MyPage Url 수정

[fix] 로그인 시 헤더에  프로필 이미지 표시

---

client/src/App.js
client/src/components/main/Navigation.js
client/src/components/shoppingComponents/ShoppingItems.js
client/src/pages/Login.js
client/src/pages/Mypage.js
client/src/pages/ShoppingCart.js
client/src/pages/SignUp.js

[feat] 회원 탈퇴기능 추가
-Mypage.js :  회원 탈퇴기능 추가
-App.js, Navigation.js : 회원가입, 쇼핑카트 url수정
-Login.js, Signup.js :  className삭제
-ShoppingItems.js : 로그인 안 했을 시 장바구니 화면 구성

[feat] 회원 탈퇴기능 추가 및 리책토링

---

client/src/components/review/ReadReviews.js
client/src/pages/ItemDetail.js

리뷰 삭제 시 별점 남아있는 버그 수정
- 리뷰 삭제 시 화면 새로고침 하는 것으로 변경했습니다.

[fix] 리뷰 삭제 시 별점 남아있는 버그 수정

---

client/src/components/main/MainHeader.js

뒤로가기 버튼 화면 표시  조건 분기 수정
- 디자인 수정
- 뒤로가기 버튼 화면 표시  조건 분기 수정

[fix] 뒤로가기 버튼 화면 표시  조건 분기 수정

---

client/src/components/review/ReviewForm.js

리뷰 Update 버그 수정
- 리뷰 수정 시 500번 에러 발생하는 버그 수정

[fix] 리뷰 Update 버그 수정

---

client/src/components/shoppingComponents/ShoppingItems.js
client/src/pages/Mypage.js
client/src/pages/ShoppingCart.js

[refactor] 장바구니코드 수정
-ShoppingItems.js
-Mypage.js
- 작성예시

[refactor] 장바구니코드 수정

---

server/EverybodyChachapark/build.gradle
server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/domain/member/controller/MemberController.java
server/EverybodyChachapark/src/main/resources/application-local.yml
server/EverybodyChachapark/src/main/resources/application-server.yml
server/EverybodyChachapark/src/main/resources/data.sql

- [Back-End] 서버 배포 대비 사전작업 및 Member Logout 코드 수정
1. add: DB세팅 템플릿 생성
- mySQL connector 의존성 추가
- mySQL 적용 profile 생성
- mySQL 적용 application.yml 설정
- 서버 실행시 자동으로 sql DML을 실행하여 DB 초기값 설정 기능 적용(spring boot sql initializr) 
2. Member Logout Controller에서 Method를 Delete -> Post, Http Status를 204(NO_CONTENT) -> 200(OK)으로 수정

[Back-End] 서버 배포 대비 사전작업 및 Member Logout 코드 수정

---

client/src/components/ui/ProductEditor.js
client/src/pages/AdminNewItem.js
client/src/pages/ItemDetail.js

상품 상세 페이지 이미지 첨부 기능 추가
- 상품 판매 상태 select 추가
- react quill 컴포넌트 분리
- ProductEditor.js
-  react quill 컴포넌트 분리
- 이미지 파일 첨부할 경우, 서버에 이미지를 post하고 받은 url을 사용하는 imageHandler 함수 추가
- 응답값으로 받은 html string 파일을 화면에 렌더링하도록 수정
- ProductEditor.js
- 이미지 사이즈 조절 기능 추가 예정

[feat] 상품 상세 페이지 이미지 첨부 기능 추가

---

client/src/pages/ItemDetail.js

상품 삭제 기능 구현
- ItemDetial.js
- 상품 삭제 기능 리팩토링

[feat] 상품 삭제 기능 구현

---

client/src/pages/ItemDetail.js

상품 상세 페이지 이미지 렌더링 크기 조절
- width: 500px로 고정

[fix] 상품 상세 페이지 이미지 렌더링 크기 조절

---

client/src/App.js
client/src/components/curating/CuratingBodyImg.js
client/src/components/itemList/ItemListItem.js
client/src/components/main/MainHeader.js
client/src/components/ui/Pagination.js

- [design] 큐레이팅 아이템 리팩토링 및 App.js 미디어 쿼리 일부 추가
- [design] 큐레이팅 아이템 리팩토링 및 App.js 미디어 쿼리 일부 추가
- [design] 아이템 타이틀 수정
- [feat] 메인헤더 로그아웃 주석 변경
- 작성예시

[design] 큐레이팅 아이템 리팩토링 및 App.js 미디어 쿼리 일부 추가

---

server/EverybodyChachapark/src/test/java/com/DuTongChitongYutong/EverybodyChachapark/slice/product/ProductControllerTest.java

- add: ProductControllerTest 오류 수정
- add: ProductControllerTest 오류 수정

add: ProductControllerTest 오류 수정

---

server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/exception/ExceptionCode.java
server/EverybodyChachapark/src/main/resources/application-testServer.yml

- add: Order ExceptionCode 오타 수정 및 TestSever 프로파일 수정
- add: Order ExceptionCode 오타 수정
- add: Application TestSever 프로파일 sql initializr 설정

add: Order ExceptionCode 오타 수정 및 TestSever 프로파일 수정

---

client/src/components/review/ReviewForm.js
client/src/pages/AdminNewItem.js
client/src/pages/ItemDetail.js

사용하지 않는 코드 삭제
- 사용하지 않는 코드 삭제
- 조건 분기 수정 (accessToken이 있을 때 => refreshToken이 있을 때)
- CSS className 수정

[refactor] 사용하지 않는 코드 삭제

---

client/src/components/newAxios.js

액세스토큰 갱신 url로 변경
-newAxios.js : 액세스토큰 갱신 url로 변경

[code] 액세스토큰 갱신 url로 변경

---

server/EverybodyChachapark/build/generated-snippets/post-member-refresh/curl-request.adoc
server/EverybodyChachapark/build/generated-snippets/post-member-refresh/http-request.adoc
server/EverybodyChachapark/build/generated-snippets/post-member-refresh/http-response.adoc
server/EverybodyChachapark/build/generated-snippets/post-member-refresh/request-headers.adoc
server/EverybodyChachapark/src/docs/asciidoc/EverbodyChachapark.adoc

- add: 리플래시 토큰 API 작성
- add: 리플래시 토큰 API 작성

add: 리플래시 토큰 API 작성

---

client/src/components/review/ReviewForm.js
client/src/pages/AdminNewItem.js
client/src/pages/ItemDetail.js

ReviewForm.js, AdminNewItem.js, ItemDetail.js 에서 newAxios 사용
- 로그인이 되지 않았을 때 로그인 페이지로 이동
- post, patch 요청에서 newAxios 사용
- ProductEditor 컴포넌트 스타일 코드 제거
- post, patch 요청에서 newAxios 사용
- 장바구니 post 요청에서 newAxios 사용
- 상품 delete 요청에서 newAxios 사용
상품 post, patch, delete 요청에서 accesstoken 값이 없어도 refreshtoken만 있으면 요청이 성공적으로 전달되는 이슈 해결 필요

[refactor] ReviewForm.js, AdminNewItem.js, ItemDetail.js 에서 newAxios 사용

---

client/src/components/main/MainHeader.js

- [refactor] MainHeader.js newAxios 사용
- [refactor] MainHeader.js Axios 인터셉터 사용 변경

[refactor] MainHeader.js newAxios 사용

---

client/src/components/shoppingComponents/ShippingInformation.js
client/src/components/shoppingComponents/ShoppingItems.js
client/src/pages/Login.js
client/src/pages/Mypage.js

axios => newAxios
axios 요청을 newAxios 로 바꾸었씁니다

[refactor] axios => newAxios

---

client/src/components/itemList/ItemListItem.js
client/src/components/ui/LoadingSpinner.js

- [refactor] 로딩 컴포넌트 추가, ItemDetail ㅡ> ItemListItem useEffect 수정
- [refactor] 로딩 컴포넌트 추가, ItemDetail ㅡ> ItemListItem useEffect 수정
- 작성예시

[refactor] 로딩 컴포넌트 추가, ItemDetail ㅡ> ItemListItem useEffect 수정

---

client/src/components/login/useLogin.js
client/src/components/newAxios.js
client/src/components/signup/Signup.styled.js
client/src/pages/Login.js
client/src/pages/SignUp.js

[refator] 스타일드컵포넌트 , 비지니스 로직 분리
-Signup.js 스타일드 컴포넌트 분리
- Login.js: 비지니스 로직 분리
- newAxios : 이름수정 newAxios => instance

[refator] 스타일드컵포넌트 , 비지니스 로직 분리

---

client/src/components/Item-detail/AdminButtonGroup.js
client/src/components/Item-detail/ItemDetail.styled.js
client/src/components/Item-detail/ProductDetail.js
client/src/components/review/ReadReviews.js
client/src/components/review/ReadReviews.styled.js
client/src/pages/ItemDetail.js

상품 세부 페이지 컴포넌트 분리
- 상품 세부 페이지에 존재하는 컴포넌트 분리
- ProductDetail.js : 상품명, 가격 등 상품에 대한 세부 정보를 화면에 렌더링하는 컴포넌트
- AdminButtonGroup.js: Admin 역할의 계정만 접근할 수 있는 버튼 컴포넌트
- styled component 분리
- ItemDetail.styled.js, ReadReviews.styled.js

[refactor] 상품 세부 페이지 컴포넌트 분리

---

client/src/components/mypage/Mypage.styled.js
client/src/components/mypage/useMypage.js
client/src/pages/Mypage.js

[refactor] 마이페이지 스타일드 컴포넌트 분리 ,비지니스로직 분리
-[Mypage.styled.js] : 스타일드 컴포넌트 분리
-[useMypage.js] : ,비지니스로직 분리

[refactor] 마이페이지 스타일드 컴포넌트 분리 ,비지니스로직 분리

---

client/src/components/itemList/ItemListItem.js
client/src/components/main/MainHeader.js

- [refactor] async await 함수 통일 및 리팩토링 및  ItemListItem productId 수정
- 작성예시

[refactor] async await 함수 통일 및 리팩토링 및  ItemListItem productId 수정

---

server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/auth/configure/SecurityConfiguration.java
server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/auth/hendler/Oauth2MemberSuccessHandler.java
server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/domain/member/controller/MemberController.java
server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/domain/member/dto/MemberDto.java

- oauth2 적용
- 구글로 로그인 가능한 oauth2 적용 되었습니다.
- 로그인 성공시 토큰발급 -> 발급 받은 토큰으로 회원 활동 가능합니다.
- 기본 설정은 비밀번호 : 123456789 / 닉네임 : 가입한 구글 이메일이 기본 입니다.
구글 계정으로 로그인하는거라 비밀번호는 크게 의미가 없을 것 같고, 닉네임은 추후 변경하여 사용 가능합니다.

[Feat] oauth2 적용

---

server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/auth/configure/SecurityConfiguration.java
server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/auth/hendler/Oauth2MemberSuccessHandler.java
server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/domain/cart/dto/CartDto.java

- oAuth2 권한 로직 수정
-구글을 통해 회원가입 시 발급받는 access-token 에 권한정보 담길 수 있도록 수정 되었습니다.

[Back-end] oAuth2 권한수정

---

client/src/components/curating/CuratingBodyImg.js
client/src/components/curating/CuratingDetail.styled.js
client/src/components/homes/Home.styled.js
client/src/components/itemList/ItemList.styled.js
client/src/components/itemList/ItemListItem.js
client/src/components/itemList/useItemList.js
client/src/pages/CuratingDetail.js
client/src/pages/Home.js
client/src/pages/ItemList.js

- 메인, 큐레이팅, 상품 목록 페이지 리팩토링, ItemListItem.js 리뷰 데이터 수정
- [refactor] 상품 목록 페이지 코드 리팩토링
- [refactor] 큐레이팅 페이지 코드 리팩토링
- [refactor] 메인 페이지 코드 리팩토링
- [docs] ItemListItem.js 리뷰 데이터 api 제외
- 작성예시
- IItemListItem.js 파일에서 기존에 상품상세, 리뷰 navigate 넘겨주는 부분 리뷰쪽은 제외하였습니다

[refactor] 메인, 큐레이팅, 상품 목록 페이지 리팩토링, ItemListItem.js 리뷰 데이터 수정

---

client/src/components/Item-detail/ProductDetail.js
client/src/components/review/ReadReviews.js
client/src/components/review/ReviewForm.js
client/src/pages/ItemDetail.js

상품 상세 페이지 및 리뷰 작성 폼 코드 리팩토링
- window.alert 수정
- ProductDetail.js
-  본인이 작성한 리뷰에만 수정 및 삭제 버튼 표시하도록 수정
-  ItemDetail.js, ReadReviews.js
- newAxios 이름 수정 및 handleSubmit 함수 수정
- 상품 목록 페이지로 돌아간 뒤 다시 상품 상세 페이지로 이동해야됨
- 해결 완료

[refactor] 상품 상세 페이지 및 리뷰 작성 폼 코드 리팩토링

---

server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/auth/hendler/Oauth2MemberSuccessHandler.java
server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/auth/jwt/JwtVerificationFilter.java
server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/domain/cart/entity/Cart.java
server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/domain/cart/fasade/CartFacade.java
server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/domain/member/service/MemberService.java
server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/domain/order/service/OrderService.java
server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/exception/ExceptionCode.java

- Oauth2 호스트 주소 변경
1. Oauth2 호스트 주소 변경되었습니다. (대현님 호스트서버 주소로 변경)
2. atk 만 보내도 회원로직 수행할 수 있도록 변경했습니다.

[Back-end] Oauth2 호스트 주소 변경

---

client/src/components/curating/CuratingBodyImg.js
client/src/components/itemList/ItemListItem.js
client/src/components/newAxios.js

- [refactor] 큐레이팅이미지 컴포넌트 리팩토링 및 상세 페이지 이동 수정 및 newAxios.js 토큰 수정
- [docs] newAxios.js 리프레쉬 토큰 제외한 액세스 토큰값 요청 수정
- [style] ItemListItem 컴포넌트 겹치는 부분 제외
- [refactor] 큐레이팅이미지 컴포넌트 리팩토링 및 상세 페이지 이동 수정
- 작성예시
- 처음에 액세스, 리프레쉬 토큰 둘 다 요청 보내는게 아닌 액세스 토큰만 넣어서 요청보내는 로직으로 수정
- 큐레이팅이미지 컴포넌트 리팩토링 및 상세 페이지 이동 불가문제 다시 수정해서 해결했습니다

[refactor] 큐레이팅이미지 컴포넌트 리팩토링 및 상세 페이지 이동 수정 및 newAxios.js 토큰 수정

---

server/EverybodyChachapark/src/docs/asciidoc/EverbodyChachapark.adoc
server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/domain/order/controller/OrderController.java
server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/domain/order/dto/OrderListPage.java
server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/domain/order/repository/OrderRepository.java
server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/domain/order/service/OrderService.java
server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/domain/product/facade/ProductFacade.java
server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/exception/ExceptionCode.java
server/EverybodyChachapark/src/test/java/com/DuTongChitongYutong/EverybodyChachapark/slice/order/OrderControllerTest.java

주문 기능 수정
- 주문 목록 조회 페이지네이션 구현 완료
- 주문할 cartId가 없는 cartList가 전달될 경우(장바구니에 있는 아무 상품도 체크하지 않고 주문할 경우) 404에러 반환("선택된 상품이 없습니다")
- ProductFacade에 있는 long => Long으로 변환
- API DOCS 수정

Feat/be/order 주문 기능 수정

---

client/package-lock.json
client/src/components/curating/CuratingBodyImg.js
client/src/components/curating/CuratingBodyImg.styled.js
client/src/components/curating/CuratingDetail.styled.js
client/src/components/homes/Home.styled.js
client/src/components/itemList/CategoryContainer.js
client/src/components/itemList/ItemListSingle.js
client/src/components/itemList/ItemListSingle.styled.js
client/src/components/itemList/useItemList.js
client/src/components/notFound/NotFound.styled.js
client/src/components/ui/MainBoxLarge.js
client/src/components/ui/MainBoxSmall.js
client/src/pages/CuratingDetail.js
client/src/pages/Home.js
client/src/pages/ItemList.js
client/src/pages/NotFound.js

- [refactor] 상품 목록, 메인, 큐레이팅 페이지 리팩토링
- [refactor] 상품 목록, 메인, 큐레이팅 페이지 리팩토링
- 작성예시
- ItemListItem.js ㅡ> ItemListSingle.js
- MainBoxL ㅡ>MainBoxLarge, MainBoxS ㅡ> MainBoxSmall 파일명 수정

[refactor] 상품 목록, 메인, 큐레이팅 페이지 리팩토링

---

client/src/components/mypage/Mypage.styled.js
client/src/components/mypage/useMemberInfomation.js
client/src/components/mypage/useMypageOrderItems.js
client/src/pages/Mypage.js

mypage 최근 주문상품 목록 생성 
-[Mypage.styled.js] : 마이페이지 스타일
-[useMypage.js → useMemberInformation.js]:이름변경, 회원의 상태를 보여줌
-[useMypageOrderItems.js] : 주문상품 데이터 받아오기

[feat]최근주문상품 목록 생성

---

server/EverybodyChachapark/src/main/resources/application-server.yml
server/EverybodyChachapark/src/main/resources/logback-spring.xml
server/db/data.sql
server/scripts/deploy.sh

- [Back-End] Back-End Server Release 문서 수정 및 배포 환경에 맞게 코드 수정
1. add: EverybodyChaChaPark Release Guide 문서 수정
2. add: 배포 Shell Scripts 코드 수정
3. add: data.sql Scripts 수정
4. feat: EC2 환경에 redis, apache web-server 설치 및 적용 완료

[Back-End] Back-End Server Release 문서 수정 및 배포 환경에 맞게 각 스크립트 내용 수정

---

client/src/components/mypage/useMemberInfomation.js
client/src/components/mypage/useMypageOrderItems.js

리프레시 토큰이 있을  때만 정보 받아오기
-useMypageInformation.js :  리프레시 토큰이 있을  때만 정보 받아오기

[add] 마이페이지 리프레시 토큰이 있을  때만 정보 받아오기

---

server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/auth/hendler/Oauth2MemberSuccessHandler.java

[Back-end] oauth2 경로변경

---

client/src/components/curating/CuratingBodyImg.styled.js
client/src/components/main/MainHeader.js

- [style] 헤더 및 큐레이팅 박스 수정
- [style] 큐레이팅 박스 길이, 헤더 z-index 추가

[style] 헤더 및 큐레이팅 박스 수정

---

client/src/components/shoppingComponents/ShoppingItems.js

수량변경 시 체크표시 초기화 되지 않도록
- [ShoppingItems.js]: 수량변경 시 체크표시 초기화 되지 않도록 수정

[add] 수량변경 시 체크표시 초기화 되지 않도록 수정

---

client/src/components/Item-detail/ProductDetail.js

중복 코드 삭제
- productDetail.js
- 라이브러리 import 관련 중복 코드 삭제

[refactor] 중복 코드 삭제

---

client/src/components/main/MainHeader.js

- [comment] 안쓰는 코드들 제거
- [comment] 안쓰는 코드들 제거
- 작성예시

[comment] MainHeader.js 안쓰는 코드들 제거

---

client/src/components/Item-detail/ItemDetail.styled.js

<p> cannot appear as a descendant of <p> 버그 해결

[fix] <p> cannot appear as a descendant of <p> 버그 해결

---

client/src/components/login/useLogin.js
client/src/components/mypage/Mypage.styled.js
client/src/components/mypage/useMemberInfomation.js
client/src/components/mypage/useMypageOrderItems.js
client/src/components/shoppingComponents/ShoppingItems.js
client/src/pages/Login.js
client/src/pages/ShoppingCart.js
client/src/pages/SignUp.js

[refacotr] 주석삭제, 미사용 라이브러리 삭제
주석삭제, 미사용 라이브러리 삭제

[refacotr] 주석삭제, 미사용 라이브러리 삭제

---

client/src/components/api/itemDetailAPI.js
client/src/components/ui/ProductEditor.js

배포를 위한 url setting
- 배포를 위한 url setting
- ProductEditor.js
- axios 수정

[refactor] 배포를 위한 url setting

---

client/src/components/login/useLogin.js
client/src/components/newAxios.js
client/src/pages/SignUp.js

[refactor] 배포용 url 변경
- [newAxios.js] 
-  [useLogin.js]
-  [SignUp.js]
*공통* : 배포용 url 변경

[refactor] 배포용 url 변경

---

client/package.json
client/src/components/api/itemAPI.js

- [refactor] 배포 URI 설정
- [refactor] 배포 URI 설정
- 작성예시

[refactor] 배포 URI 설정

---

client/src/components/login/useLogin.js
server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/auth/configure/SecurityConfiguration.java
server/EverybodyChachapark/src/main/java/com/DuTongChitongYutong/EverybodyChachapark/auth/jwt/JwtAuthenticationFilter.java

- [Fix] 배포 성공, CORS 문제 해결
- fix: 배포 성공, CORS 문제 해결
1. SecurityConfiguration.filterChain()에서 ``` .cors().configurationSource(corsConfigurationSource()).and()```으로 직접 명시를 하여 적용
2. corsConfigurationSource() 설정에 ```configuration.addAllowedOriginPattern(domain);``` 으로 ACCESS-CONTROL-ORGIN 주소 선언 방식을 Pattern 으로 적용
3. ★중요★ JwtAuthenticationFilter 클래스에 로그인 성공시 토큰을 헤더에 담아 응답하는 코드 중 임의로 작성한 ```response.setHeader("Access-Control-Expose-Headers", accessToken);``` 헤더 Set 코드를 삭제함으로써 클라이언트에서 헤더값을 Exposed 못하던 문제 해결  
<br>
> 교훈 - CORS에서 명시한 해더는 건드리지 말아야 하는 것을 깨닫게 되었습니다.
-

[Fix] 배포 성공, CORS 문제 해결

---

client/src/components/api/itemAPI.js
client/src/components/curating/CuratingBodyImg.styled.js
client/src/components/itemList/ItemList.styled.js
client/src/components/itemList/ItemListSingle.styled.js
client/src/components/itemList/useItemList.js
client/src/components/mapApi/Location.js
client/src/components/ui/SubCarousel.js

- [refactor] 상품 및 큐레이팅 페이지 css 수정, 배포 URI 추가
- [refactor] 상품 및 큐레이팅 페이지 css 수정
- [docs] 배포 URI 추가
- 작성예시

[refactor] 상품 및 큐레이팅 페이지 css 수정, 배포 URI 추가

---

client/package.json
client/src/App.js
client/src/components/api/itemAPI.js
client/src/components/login/useLogin.js
client/src/components/newAxios.js
client/src/components/review/ReadReviews.styled.js
client/src/components/ui/LoadingSpinner.js
client/src/components/ui/ProductEditor.js
client/src/pages/SignUp.js

리뷰 수정 삭제 버튼 디자인 수정 및 모바일 환경을 위한 디자인 수정
- 모바일 환경을 위한 디자인 수정
- App.js, LoadingSpinner.js
- 리뷰 수정, 삭제 버튼 디자인 수정
- ReadReviews.styled.js

[design] 리뷰 수정, 삭제 버튼 디자인 수정 및 모바일 환경을 위한 디자인 수정

---

client/src/components/mypage/useMemberInfomation.js
client/src/components/newAxios.js
client/src/components/shoppingComponents/DaumPostCode.js
client/src/components/shoppingComponents/ShippingInformation.js
client/src/pages/SignUp.js

[add] 오류사항 1차 수정
- [useMemberInfomation.js]: 탈퇴시 알림창 띄어주기
- [newAxios.js] : withCredentails 추가 및 URL변수 사용
- [DaumPostCode.js]: 닫기 버튼 추가
- [ShippingInformation.js]: 팝업창 분리
- [[SignUp.js]:회원가입 완료시 팝업창

[add] 오류사항 1차 수정

---

client/src/App.js
client/src/components/Item-detail/AdminButtonGroup.js
client/src/components/main/MainHeader.js
client/src/pages/AdminNewItem.js

[design] 모바일 환경을 위한 디자인 수정
[fix] 상품 등록, 수정, 삭제 후 상품 목록에 반영되도록 수정
**[design]**
- App.js
- MainLayout 컴포넌트 가로 길이 수정
- MainHeader.js
- 모바일 환경에서 margin 값 수정
- 주석 제거
**[fix]**
- AdminButtonGroup.js
- delete 요청 후에 성공하면 상품 목록 페이지로 이동
- post 또는 patch 요청 후에 성공하면 상품 목록 페이지로 이동

[design] 모바일 환경을 위한 디자인 수정  [fix] 상품 등록, 수정, 삭제 후 상품 목록에 반영되도록 수정

---

client/src/pages/SignUp.js

[refactor] 닉네임 비밀번호 제한 글자수 수정
-[SignUp.js]: 회원가입 닉네임 비밀번호 제한 글자수 수정

[refactor] 회원가입 닉네임 비밀번호 제한 글자수 수정

---

client/src/components/mypage/useMemberInfomation.js
client/src/pages/SignUp.js

[front-end] 4차배포
회원가입시 닉네임,비밀번호 글자수 제한 수정

[front-end] 4차배포
